### ISSUE TITLE
Refactor Program Service to Get Rid Of GRPC

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/program-service#396]
## Goals
Replace all GRPCs functions with REST API.

**Comment by joneubank** [comment]
The list of RPC services that need to be replaced are found in https://github.com/icgc-argo/program-service/blob/develop/src/main/proto/ProgramService.proto

```proto
service ProgramService {

  rpc CreateProgram(CreateProgramRequest) returns (CreateProgramResponse);
  rpc RemoveProgram(RemoveProgramRequest) returns (google.protobuf.Empty);
  rpc UpdateProgram(UpdateProgramRequest) returns (UpdateProgramResponse);
  rpc ListPrograms(google.protobuf.Empty) returns (ListProgramsResponse);
  rpc GetProgram(GetProgramRequest) returns (GetProgramResponse);
  rpc ActivateProgram(ActivateProgramRequest) returns (GetProgramResponse);

  rpc InviteUser(InviteUserRequest) returns (InviteUserResponse);
  rpc GetJoinProgramInvite(GetJoinProgramInviteRequest) returns (GetJoinProgramInviteResponse);
  rpc JoinProgram(JoinProgramRequest) returns (JoinProgramResponse);

  rpc RemoveUser(RemoveUserRequest) returns (RemoveUserResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc UpdateUser(UpdateUserRequest) returns (google.protobuf.Empty);

  rpc ListCancers (google.protobuf.Empty) returns (ListCancersResponse);
  rpc ListPrimarySites (google.protobuf.Empty) returns (ListPrimarySitesResponse);
  rpc ListCountries (google.protobuf.Empty) returns (ListCountriesResponse);
  rpc ListRegions (google.protobuf.Empty) returns (ListRegionsResponse);
  rpc ListInstitutions (google.protobuf.Empty) returns (ListInstitutionsResponse);
  rpc AddInstitutions (AddInstitutionsRequest) returns (AddInstitutionsResponse);

}
```

We will work on this in chunks, first we will add the 5x CRUD requests for Programs then review the process and make changes as necessary.

The work required should be to create new REST endpoints in a new controller (not public) for these actions that parse request data into the DTO objects degined by the protobuf, and then send this data through to the existing [ProgramService](https://github.com/icgc-argo/program-service/blob/develop/src/main/java/org/icgc/argo/program_service/services/ProgramService.java) exposed through the [ProgramServiceFacade](https://github.com/icgc-argo/program-service/blob/develop/src/main/java/org/icgc/argo/program_service/services/ProgramServiceFacade.java). Because all the existing code is designed to handle incoming protobuff generated DTOs and then convert them to the DB model, it may be easiest to continue using these objects.

- [ ] CreateProgram(CreateProgramRequest) returns (CreateProgramResponse);
- [ ] RemoveProgram(RemoveProgramRequest) returns (google.protobuf.Empty);
- [ ] UpdateProgram(UpdateProgramRequest) returns (UpdateProgramResponse);
- [ ] ListPrograms(google.protobuf.Empty) returns (ListProgramsResponse);
- [ ] GetProgram(GetProgramRequest) returns (GetProgramResponse);

**Comment by Buwujiu** [comment]
Transferred into en EPIC: https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/program-service/399, this is no longer needed, closing.
